### PR TITLE
Add pysander recipe

### PR DESCRIPTION
**Pull request by swails**

### CODE REVIEW

**Comment by swails** [comment]
This is the pysander recipe I used, and it worked on both Mac and Linux.  I can probably get it to work on Windows too if I cross-compile libsander.dll with mingw... but I'll wait on that.

**Comment by hainm** [comment]
Thanks. I will test (so drunk now, lol).

**Comment by hainm** [comment]
@swails just edited my reply. :d

**Comment by swails** [comment]
I added notes on how to get this to work (it basically requires Amber to already be installed).  But other than that, there's really not much else to do.  The trick now for me is just how to build the libsander.so and libsanderles.so files.  I'm keeping my trials and errors inside the notes section of the README file.

**Comment by hainm** [comment]
Thanks. I am in conference with very low wifi. So I will try when possible.

**Pull request merged**
